# Generated by Django 4.2.4 on 2024-08-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descr',
            new_name='description',
        ),
    ]
